# Generated by Django 2.0 on 2018-10-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('GameCode', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('GameHome', models.CharField(blank=True, max_length=50)),
                ('GameAway', models.CharField(blank=True, max_length=50)),
                ('StadiumPlanned', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameTournament',
            fields=[
                ('TournamentId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TournamentCountry', models.CharField(max_length=100)),
                ('TournamentName', models.CharField(max_length=100)),
                ('Organization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('StadiumCode', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='GameTournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjk.GameTournament'),
        ),
    ]
