# Generated by Django 2.0 on 2018-10-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjk', '0002_stadiums_stadiumname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiums',
            name='StadiumCapacity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
