# Generated by Django 2.0 on 2018-10-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjk', '0003_stadiums_stadiumcapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiums',
            name='StadiumCity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadiums',
            name='StadiumFieldType',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
