# Generated by Django 2.0 on 2018-10-25 15:06

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('bjk', '0005_stadiums_stadiumfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FixedCardNumber', models.CharField(blank=True, max_length=20, verbose_name='Sabit Kart NO')),
                ('IdentityNum', models.CharField(blank=True, max_length=20, verbose_name='TC Kimlik NO')),
                ('IsOutlander', models.BooleanField(default=0, verbose_name='Yabancı mı?')),
                ('IndividualGroup', models.CharField(choices=[('2', 'GRUP-2'), ('1', 'GRUP-1')], max_length=50, verbose_name='Kişi Grubu')),
                ('IndividualCategory', models.CharField(choices=[('2', 'GRUP-2'), ('1', 'GRUP-1')], max_length=50, verbose_name='Kişi Grubu')),
                ('LicenceNumber', models.BigIntegerField(verbose_name='Lisan Numarası')),
                ('IndividualFirstName', models.CharField(max_length=30, verbose_name='Adı')),
                ('IndividualLastName', models.CharField(max_length=30, verbose_name='SoyAdı')),
                ('IndividualCompany', models.CharField(max_length=30, verbose_name='Adı')),
                ('IndividualJobTitle', models.CharField(max_length=30, verbose_name='Görev')),
                ('IndividualShirtNumber', models.BigIntegerField(verbose_name='Yelek No')),
                ('IndividualPhoneNumber', models.CharField(max_length=10, verbose_name='Telefon No')),
                ('IndividualEmailAddress', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Kişi Giriş ve Düzeltme',
                'verbose_name_plural': 'Kişi Giriş ve Düzeltme',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('PartnerId', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Kurum Kodu')),
                ('PartnerName', models.CharField(max_length=250, verbose_name='Kurum Adı')),
            ],
            options={
                'verbose_name': 'Kurumlar',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Maçlar', 'verbose_name_plural': 'Maçlar'},
        ),
        migrations.AlterModelOptions(
            name='gametournament',
            options={'verbose_name': 'Ligler & Turnuvalar', 'verbose_name_plural': 'Ligler & Turnuvalar'},
        ),
        migrations.AlterModelOptions(
            name='stadiums',
            options={'verbose_name': 'Stadyum'},
        ),
        migrations.AddField(
            model_name='game',
            name='GamePlannedDate',
            field=models.DateField(default=timezone.now, verbose_name='Plankandığı Tarih'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='GamePlannedTime',
            field=models.TimeField(default=timezone.now, verbose_name='Planlandığı Saat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='GameAway',
            field=models.CharField(blank=True, max_length=50, verbose_name='Misafir'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameCode',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Maç Kodu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameHome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ev Sahini'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameTournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjk.GameTournament', verbose_name='Lig'),
        ),
        migrations.AlterField(
            model_name='game',
            name='StadiumPlanned',
            field=models.CharField(blank=True, max_length=50, verbose_name='Planlanan Stadyum'),
        ),
        migrations.AlterField(
            model_name='stadiums',
            name='StadiumCode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Stadyum Kodu'),
        ),
        migrations.AlterField(
            model_name='stadiums',
            name='StadiumName',
            field=models.CharField(max_length=200, verbose_name='Stadyum Adı'),
        ),
    ]
