# Generated by Django 2.0 on 2018-10-25 15:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bjk', '0007_auto_20181025_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GamePlannedDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Planlandığı Tarih'),
        ),
        migrations.AlterField(
            model_name='game',
            name='GamePlannedTime',
            field=models.TimeField(default=datetime.timedelta, verbose_name='Planlandığı Saat'),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='IndividualCategory',
            field=models.CharField(choices=[('2', 'GRUP-2'), ('1', 'GRUP-1')], max_length=50, verbose_name='Kişi Grubu'),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='IndividualGroup',
            field=models.CharField(choices=[('2', 'GRUP-2'), ('1', 'GRUP-1')], max_length=50, verbose_name='Kişi Grubu'),
        ),
    ]
