# Generated by Django 2.0 on 2018-10-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjk', '0010_auto_20181025_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='PartnerAddressAdddresLine',
            field=models.CharField(default=1, max_length=50, verbose_name='Adres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='PartnerAddressCity',
            field=models.CharField(default=1, max_length=50, verbose_name='Şehirr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='PartnerAddressCountry',
            field=models.CharField(default=1, max_length=50, verbose_name='Ülke'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='PartnerAddressDistrict',
            field=models.CharField(default=1, max_length=50, verbose_name='İlçe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acreditationforindividuals',
            name='AcreditationForIndividualCategory',
            field=models.CharField(choices=[('1', 'Kategori-1'), ('2', 'Kategori-2')], max_length=50, verbose_name='Kişi Grubu'),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='IndividualCategory',
            field=models.CharField(choices=[('1', 'Kategori-1'), ('2', 'Kategori-2')], max_length=50, verbose_name='Kategori'),
        ),
    ]
