# Generated by Django 2.1.2 on 2018-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('JobTitleCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('JobTitleDescription', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
