# Generated by Django 2.1.2 on 2018-10-20 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShiftManager', '0002_auto_20181021_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'verbose_name': 'Ünvan', 'verbose_name_plural': 'Ünvanlar'},
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='CreatedUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
