# Generated by Django 2.1.2 on 2018-10-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManager', '0004_auto_20181021_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttypes',
            options={'verbose_name': 'Shift Tipi', 'verbose_name_plural': 'Shift Tipi'},
        ),
    ]
