# Generated by Django 2.1.2 on 2018-10-21 17:33

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0009_auto_20170124_1125'),
        ('ShiftManager', '0005_auto_20181021_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttypes',
            name='Approve',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
    ]
