# Generated by Django 2.1.2 on 2018-10-21 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShiftManager', '0006_shifttypes_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveStartDate', models.DateField()),
                ('LeaveEndDate', models.DateField()),
                ('LeaveDesc', models.TextField(max_length=100)),
                ('IsBlocked', models.BooleanField(default=1, verbose_name='Kullanım Dışı')),
                ('CreatedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('LeaveType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiftManager.LeaveType')),
            ],
        ),
    ]
