# Generated by Django 2.1.2 on 2018-10-21 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('river', '0009_auto_20170124_1125'),
        ('ShiftManager', '0007_leaveapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'verbose_name': 'Yıllık İzin', 'verbose_name_plural': 'Yıllık İzin'},
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='CreatedUser',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='EmployeeCode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel Kodu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='StateStatus',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
    ]
