# Generated by Django 2.1.2 on 2018-10-21 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManager', '0008_auto_20181021_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='CreatedDate',
            field=models.DateField(default=1, verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='IsBlocked',
            field=models.BooleanField(verbose_name='Kullanım Dışı'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='LeaveDesc',
            field=models.TextField(max_length=100, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='LeaveEndDate',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='LeaveStartDate',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='LeaveType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiftManager.LeaveType', verbose_name='İzin Tipi'),
        ),
    ]
