# Generated by Django 2.1.2 on 2018-10-21 23:10

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftManager', '0009_auto_20181022_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='CreatedDate',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='IsBlocked',
            field=models.BooleanField(default=0, verbose_name='Kullanım Dışı'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='StateStatus',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State', verbose_name='Status'),
        ),
    ]
